version: '3.3'

services:

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    depends_on:
      - web-app1
      - web-app2
      - appsmith
    volumes:
      - ./config/nginx-proxy.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # web-app1 service
  web-app1:
    image: nginx
    container_name: web-app1
    volumes:
      - ./web-app1/site-content:/usr/share/nginx/html
    ports:
      - 8081:80

  # web-app2 service
  web-app2:
    image: nginx
    container_name: web-app2
    volumes:
      - ./web-app2/site-content:/usr/share/nginx/html
    ports:
      - 8082:80

  # appsmith service
  appsmith:
    image: appsmith/appsmith-ce:v1.5.25
    container_name: appsmith
    environment:
      - APPSMITH_DISABLE_TELEMETRY=true
      - APPSMITH_DISABLE_INTERCOM=true
    ports:
      - 9090:80
      - 9443:443
      - 9001:9001
    volumes:
      - ./stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped
